### ISSUE TITLE
pandas cheat-sheet link not working

### ISSUE THREAD

**Issue by tsmdt** [zbmed/2023-2024-ZK_Data_Librarian_Modul_3#2]
Hi,

der [Cheat-Sheet](http://datacamp-community-prod.s3.amazonaws.com/dbed353d-2757-4617-8206-8767ab379ab3) link in (→ content/basics/pandas/_index.md) wirft einen Fehler:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5SKM0HP83Y036JHC</RequestId>
<HostId>VhqVRLrXuIkCwvMP1V3rKlV/2T4lo7MjCykKsd2tBgYFqB0aCN2eOiiYsGYcqMx+2dBo+np2rEg=</HostId>
</Error>`

**Comment by konrad** [comment]
Danke, @th-schmidt. Habe den Link gefixt.
